changed function name get() to get_url() due to library conflicts
2015-08-14 09:39:28,250 - t.184 - DEBUG - ln.25 - Opening DB connection
2015-08-14 09:39:28,250 - t.3112 - INFO - ln.277 - Saving blog: u'artsenravenbrave.tumblr.com'
2015-08-14 09:39:28,250 - t.5060 - DEBUG - ln.25 - Opening DB connection
2015-08-14 09:39:28,250 - t.960 - DEBUG - ln.25 - Opening DB connection
2015-08-14 09:39:28,250 - t.1848 - DEBUG - ln.25 - Opening DB connection
2015-08-14 09:39:28,250 - t.2560 - DEBUG - ln.25 - Opening DB connection
2015-08-14 09:39:28,250 - t.3112 - DEBUG - ln.25 - Opening DB connection
2015-08-14 09:39:28,296 - t.184 - DEBUG - ln.43 - Session connected to DB
2015-08-14 09:39:28,312 - t.184 - DEBUG - ln.552 - stripped_url: u'the303.tumblr.com'
2015-08-14 09:39:28,312 - t.184 - CRITICAL - ln.301 - Unhandled exception in save_blog()!
2015-08-14 09:39:28,312 - t.184 - ERROR - ln.302 - global name 'requests' is not defined
Traceback (most recent call last):
  File "Z:\tumblr_api_to_db\get_posts.py", line 283, in save_blog
    blog = tumblr_blog(session, consumer_key = config.consumer_key, blog_url=blog_url)
  File "Z:\tumblr_api_to_db\get_posts.py", line 48, in __init__
    self.load_info()
  File "Z:\tumblr_api_to_db\get_posts.py", line 72, in load_info
    info_json = get(info_url)
  File "Z:\tumblr_api_to_db\utils.py", line 312, in get
    get_tuple = get_requests(url)
  File "Z:\tumblr_api_to_db\utils.py", line 336, in get_requests
    except requests.ConnectionError, err:
NameError: global name 'requests' is not defined
2015-08-14 09:39:28,358 - t.184 - INFO - ln.277 - Saving blog: u'negativefade.tumblr.com'
2015-08-14 09:39:28,375 - t.2616 - CRITICAL - ln.384 - Unhandled exception!
2015-08-14 09:39:28,375 - t.184 - DEBUG - ln.25 - Opening DB connection
2015-08-14 09:39:28,375 - t.2616 - ERROR - ln.385 - global name 'requests' is not defined
Traceback (most recent call last):
  File "Z:\tumblr_api_to_db\get_posts.py", line 379, in main
    save_blogs()
  File "Z:\tumblr_api_to_db\get_posts.py", line 319, in save_blogs
    results = pool.map(save_blog, blog_url_list)
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
NameError: global name 'requests' is not defined