fix for crash on bad imgur link
2015-08-19 10:17:12,632 - t.1808 - WARNING - ln.367 - External links handling not yet implimented, fix this!
2015-08-19 10:17:12,632 - t.1808 - DEBUG - ln.371 - handle_links() all_post_links[u'https://imgur.com/']
2015-08-19 10:17:12,632 - t.1808 - DEBUG - ln.375 - handle_links() non_tumblr_links: [u'https://imgur.com/']
2015-08-19 10:17:12,632 - t.1808 - DEBUG - ln.381 - new_links: [u'https://imgur.com/']
2015-08-19 10:17:12,632 - t.1808 - DEBUG - ln.384 - Processing link:u'https://imgur.com/'
2015-08-19 10:17:12,632 - t.1808 - DEBUG - ln.405 - Link is imgur: u'https://imgur.com/'
2015-08-19 10:17:12,632 - t.1808 - DEBUG - ln.101 - Handling imgur link:u'https://imgur.com/'
2015-08-19 10:17:12,632 - t.1808 - ERROR - ln.75 - Could not parse image(s) link! u'https://imgur.com/'
2015-08-19 10:17:12,632 - t.1808 - CRITICAL - ln.70 - Unhandled exception in save_blog()!
2015-08-19 10:17:12,632 - t.1808 - ERROR - ln.71 -
Traceback (most recent call last):
  File "Z:\tumblr_api_to_db\get_media.py", line 44, in process_one_new_posts_media
    media_id_list = save_media(session,raw_post_dict)
  File "Z:\tumblr_api_to_db\media_handlers.py", line 93, in save_media
    remote_link_id_list = link_handlers.handle_links(session,post_dict)# TODO FIXME
  File "Z:\tumblr_api_to_db\link_handlers.py", line 406, in handle_links
    media_id_list += imgur.save_imgur(session,link)
  File "Z:\tumblr_api_to_db\imgur.py", line 107, in save_imgur
    return save_imgur_images(session,link)
  File "Z:\tumblr_api_to_db\imgur.py", line 76, in save_imgur_images
    assert(False)# we need to fix things if this happens
AssertionError
2015-08-19 10:19:26,868 - t.2516 - ERROR - ln.298 - [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Traceback (most recent call last):
  File "Z:\tumblr_api_to_db\utils.py", line 223, in getwithinfo
    context=ctx
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "C:\Python27\lib\httplib.py", line 1132, in getresponse
    response.begin()
  File "C:\Python27\lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "C:\Python27\lib\httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "C:\Python27\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
2015-08-19 10:19:26,882 - t.2516 - ERROR - ln.300 - getwithinfo() caught an exception
2015-08-19 10:19:26,898 - t.2516 - ERROR - ln.301 - getwithinfo() repr(err):error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')
2015-08-19 10:19:26,898 - t.2516 - ERROR - ln.302 - getwithinfo() str(err):[Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
2015-08-19 10:19:26,898 - t.2516 - ERROR - ln.303 - getwithinfo() type(err):<class 'socket.error'>
2015-08-19 10:19:36,898 - t.2516 - DEBUG - ln.210 - Attempt 2 for URL: u'http://musicdata.miqiu.com/classic/Tubthumping.mp3'
2015-08-19 10:20:36,914 - t.2516 - ERROR - ln.298 - [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Traceback (most recent call last):
  File "Z:\tumblr_api_to_db\utils.py", line 223, in getwithinfo
    context=ctx
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "C:\Python27\lib\httplib.py", line 1132, in getresponse
    response.begin()
  File "C:\Python27\lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "C:\Python27\lib\httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "C:\Python27\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
2015-08-19 10:20:36,930 - t.2516 - ERROR - ln.300 - getwithinfo() caught an exception
2015-08-19 10:20:36,930 - t.2516 - ERROR - ln.301 - getwithinfo() repr(err):error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')
2015-08-19 10:20:36,946 - t.2516 - ERROR - ln.302 - getwithinfo() str(err):[Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
2015-08-19 10:20:36,946 - t.2516 - ERROR - ln.303 - getwithinfo() type(err):<class 'socket.error'>
2015-08-19 10:20:46,946 - t.2516 - DEBUG - ln.210 - Attempt 3 for URL: u'http://musicdata.miqiu.com/classic/Tubthumping.mp3'