moved unused scripts to depricated/ fix for youtube_dl_common crash
2015-10-27 10:08:19,289 - t.3060 - DEBUG - ln.763 - Post is video
2015-10-27 10:08:19,289 - t.3060 - DEBUG - ln.770 - Post is tumblr video
2015-10-27 10:08:19,305 - t.3060 - DEBUG - ln.223 - Processing tumblr video
2015-10-27 10:08:19,305 - t.3060 - DEBUG - ln.225 - video_page: u'http://fallfeatherspony.tumblr.com/post/109567450555/askloona-\u1d1b-\u029c-\u1d07-\u028f-\u1d21-\u1d07-\u0280-\u1d07'
2015-10-27 10:08:19,305 - t.3060 - DEBUG - ln.48 - download_url: u'http://fallfeatherspony.tumblr.com/post/109567450555/askloona-\u1d1b-\u029c-\u1d07-\u028f-\u1d21-\u1d07-\u0280-\u1d07'
2015-10-27 10:08:19,335 - t.3060 - DEBUG - ln.89 - command: ['youtube-dl\\youtube-dl.exe', '-i', '--restrict-filenames', '--max-filesize', '500m', '--write-info-json', '--write-annotations', '-o', 'Y:\\winvm\\download\\temp\\1445954899305.565B47715A1B32E57CF881438F6E458CC4288A6EC30C5F191A0FAED6C066E37D9620799F51AE261B1FD9FB05796AB8A7CE78DFF34D1AD13553576E05307B50E5.%(ext)s', u'http://fallfeatherspony.tumblr.com/post/109567450555/askloona-\u1d1b-\u029c-\u1d07-\u028f-\u1d21-\u1d07-\u0280-\u1d07']
2015-10-27 10:08:19,335 - t.3060 - CRITICAL - ln.81 - Unhandled exception in save_blog()!
2015-10-27 10:08:19,335 - t.3060 - ERROR - ln.82 - 'ascii' codec can't encode character u'\u1d1b' in position 347: ordinal not in range(128)
Traceback (most recent call last):
  File "Y:\winvm\tumblr_api_to_db\get_media.py", line 54, in process_one_new_posts_media
    blog_settings_dict = blog_settings_dict,
  File "Y:\winvm\tumblr_api_to_db\media_handlers.py", line 111, in save_media
    video_embed_id_list = video_handlers.handle_video_posts(session,post_dict)
  File "Y:\winvm\tumblr_api_to_db\video_handlers.py", line 771, in handle_video_posts
    return handle_tumblr_videos(session,post_dict)
  File "Y:\winvm\tumblr_api_to_db\video_handlers.py", line 232, in handle_tumblr_videos
    extractor_used="video_handlers.handle_tumblr_videos()",
  File "Y:\winvm\tumblr_api_to_db\yt_dl_common.py", line 39, in run_yt_dl_multiple
    video_id=video_id,
  File "Y:\winvm\tumblr_api_to_db\yt_dl_common.py", line 91, in run_yt_dl_single
    command_result = subprocess.call(command)
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u1d1b' in position 347: ordinal not in range(128)